grpc:
  server:
    port: 59081
  client:
    shopping-store:
      address: 'static://localhost:59081'
      negotiationType: PLAINTEXT

server:
  port: 0

logging:
  level:
    ru.yandex.practicum: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver