server:
  port: 8888

eureka:
  client:
    serviceUrl:
      registerWithEureka: true
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}