

spring:
  application:
    name: aggregator
  kafka:                    # ← kafka должна быть на одном уровне с application
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group

  # config:
  #  import: 'configserver:http://localhost:8888'

