spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-home-tech
    username: smart-home-tech
    password: smart-home-tech

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: analyzer-group

server:  # ← добавляем секцию server
  port: 8082